run: 
	python .\src\img-morp.py -e .\input\SE1.txt .\input\f1.txt .\output\ef1_e1.txt
	python .\src\img-morp.py -e .\input\SE2.txt .\input\f2.txt .\output\ef2_e2.txt
	python .\src\img-morp.py -e .\input\SE3.txt .\input\f3.txt .\output\ef3_e2.txt
	python .\src\img-morp.py -e .\input\SE4.txt .\input\f3.txt .\output\ef3_e3.txt
	python .\src\img-morp.py -e .\input\SE5.txt .\input\f3.txt .\output\ef3_e4.txt
	python .\src\img-morp.py -e .\input\SE6.txt .\input\f3.txt .\output\ef3_e5.txt
	python .\src\img-morp.py -d .\input\SE4.txt .\input\f3.txt .\output\df3_d3.txt
	python .\src\img-morp.py -d .\input\SE5.txt .\input\f3.txt .\output\df3_d4.txt
	python .\src\img-morp.py -d .\input\SE6.txt .\input\f3.txt .\output\df3_d5.txt
	python .\src\img-morp.py -d .\input\SE4.txt .\output\ef3_e3.txt .\output\of3_o3.txt
	python .\src\img-morp.py -d .\input\SE5.txt .\output\ef3_e4.txt .\output\of3_o4.txt
	python .\src\img-morp.py -d .\input\SE_asym_no_origin.txt .\input\fp.txt .\output\fingerprint-output.txt
	python .\src\img-morp.py -d .\input\SE7.txt .\input\covid.txt .\output\covid.txt
	python .\src\img-morp.py -e .\input\SE8.txt .\input\wolf.txt .\output\wolf_erosion.txt
	python .\src\img-morp.py -d .\input\SE9.txt .\input\roots.txt .\output\roots_dilated.txt 