run: 
	python .\img-morp.py -e .\SE1.txt .\f1.txt ef1_e1.txt
	python .\img-morp.py -e .\SE2.txt .\f2.txt ef2_e2.txt
	python .\img-morp.py -e .\SE3.txt .\f3.txt ef3_e2.txt
	python .\img-morp.py -e .\SE4.txt .\f3.txt ef3_e3.txt
	python .\img-morp.py -e .\SE5.txt .\f3.txt ef3_e4.txt
	python .\img-morp.py -e .\SE6.txt .\f3.txt ef3_e5.txt
	python .\img-morp.py -d .\SE4.txt .\f3.txt df3_d3.txt
	python .\img-morp.py -d .\SE5.txt .\f3.txt df3_d4.txt
	python .\img-morp.py -d .\SE6.txt .\f3.txt df3_d5.txt
	python .\img-morp.py -d .\SE4.txt .\ef3_e3.txt of3_o3.txt
	python .\img-morp.py -d .\SE5.txt .\ef3_e4.txt of3_o4.txt
	python .\img-morp.py -d .\SE_asym_no_origin.txt .\fp.txt fingerprint-output.txt
	python .\img-morp.py -d .\SE7.txt .\corona_output.txt corona_output.txt
	python .\img-morp.py -e .\SE8.txt .\wolf.txt wolf_erosion.txt
	python .\img-morp.py -d .\SE9.txt .\roots.txt roots_dilated.txt 