run: 
	python3 hw2.py -i ..\input\f1_dinv.txt -o ..\output\f1_dinv_neighbor_4.txt -n 4
	python3 hw2.py -i ..\input\f1_dinv.txt -o ..\output\f1_dinv_neighbor_8.txt -n 8
	python3 hw2.py -i ..\input\f2.txt -o ..\output\f2_neighbor_4.txt -n 4
	python3 hw2.py -i ..\input\f2.txt -o ..\output\f2_neighbor_8.txt -n 8